import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { useEffect, useState } from 'react'
import dynamic from 'next/dynamic'
import useAgora from '../hooks/useAgora'
import MediaPlayer from '../components/MediaPlayer'

export default function Home() {
  const [isJoinClicked, setIsJoinClicked] = useState(false)
  const [isLeaveClicked, setIsLeaveClicked] = useState(false)
  const [localVideoTrack, setLocalVideoTrack] = useState(undefined)
  const [localAudioTrack, setLocalAudioTrack] = useState(undefined)
  const [remoteUsers, setRemoteUsers] = useState([])
  const APPID = '03dbe558495c4bacbe2eb4f56794047b'

  var AgoraRTC

  // const agora = async () => {
  //   var AgoraRTC = (await import('agora-rtc-sdk-ng')).default
  // }

  // useEffect(() => async () => agora())
  var rtc = {
    client: null,
    localAudioTrack: null,
    localVideoTrack: null,
  }

  if (process.browser)
    import('agora-rtc-sdk-ng').then((obj) => {
      AgoraRTC = obj
      rtc.client = AgoraRTC.createClient({ mode: 'rtc', codec: 'vp8' })
      const {
        localAudioTrack,
        localVideoTrack,
        leave,
        join,
        joinState,
        remoteUsers,
      } = useAgora(rtc.client)
    })


  var options = {
    appId: APPID,
    channel: 'testChannel',
    token:
      '00603dbe558495c4bacbe2eb4f56794047bIAAB5dIEfpx4mfqJXBrNo0nUKAG2By4igQZDiE7VRHYnhXZXrgMAAAAAEAD/3NMfr/6xYAEAAQCv/rFg',
  }



  //create client

  if (localAudioTrack) setLocalAudioTrack(localAudioTrack)
  if (localVideoTrack) setLocalVideoTrack(localVideoTrack)
  if (remoteUsers.length) setRemoteUsers(remoteUsers)

  if (isJoinClicked) join(options.appId, options.channel, options.token)
  if (isLeaveClicked) leave()

  return (
    <div className={styles.container}>
      <Head>
        <title>TrueInfo demo</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Welcome to trueinfo video call demo</h1>
      <button
        onClick={() => setIsJoinClicked(true)}
        style={{ backgroundColor: 'greeen' }}
      >
        Join Call
      </button>
      <button onClick={() => setIsLeaveClicked(true)}>LeaveCall</button>
      <div id='me' style={{ width: '500px', height: '500px' }}>
        <MediaPlayer
          videoTrack={localVideoTrack}
          audioTrack={localAudioTrack}
        />
      </div>
      <div id='remote-container'>
        {remoteUsers?.map((user) => (
          <div key={user.id}>
            <p>Remoter user id: {user.id}</p>
            <MediaPlayer
              videoTrack={user.videoTrack}
              audioTrack={user.audioTrack}
            />
          </div>
        ))}
      </div>
    </div>
  )
}
